# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run unit tests"
  lane :unit_tests do |options|
    gradle(task: "fole:test", build_type: "Debug")
  end

  desc "Run instrumentation tests in Firebase Test Lab"
  lane :instrumentation_tests_testlab do
    gradle(task: "sample:assemble", build_type: "Debug")
    gradle(task: "sample:assemble", build_type: "DebugAndroidTest")
    run_tests_firebase_testlab(
      project_id: "fole-34243",
      model: "Nexus6P",
      version: "27",
      delete_firebase_files: true)
  end
end
